name: BkpXDB
services:
    bkpxdb:
        image: ecespedes/bkpxdb:${VER:-latest}
        container_name: bkpxdb-dev
        hostname: bkpxdb-dev
        restart: always
        ports:
            - ${PORT_M:-3306}:3306
            - ${PORT_P:-5432}:5432
        volumes:
            # Volúmenes de Directorios
            - ./data/bkp_db/:/app/bkp_db:rw
            - ./src/list:/app/scripts/list:rw
            - ./logs/cron:/var/log/cron/:rw
            - ./logs/app:/var/log/app/:rw
            #Volumen de Archivos
            - ./data/config/bkpxdb-cron:/etc/cron.d/bkpxdb-cron
            - ./src/crontab:/app/crontab/crontab:rw
            - ./src/.conf:/app/scripts/.conf:rw
            - ./src/backup.sh:/app/scripts/backup.sh:rw
